import { useEffect, useState, useRef, useMemo, useDeferredValue } from 'react';
import toast from 'react-hot-toast';
import Swal from 'sweetalert2';
import './Categories.css';
import { useApplication, useInfrastructure } from '../../providers/DependencyProvider.tsx';
import { useAuth } from '../../context/AuthContext.tsx';
import type { Category } from '../../../domain/entities/Category.ts';
import { uploadCategoryImage, deleteCategoryStorageAssets } from '../../../infrastructure/index.ts';
import type {
  CategoryFormData,
  CategorySortKey,
  CategoryView,
  CategoryViewMode,
} from './types/CategoryPageTypes.ts';
import { CalculateTrend, GetAutoGeneratedStyles } from './utils/categoryPresentationUtils.ts';
import { CategoryPageHeader } from './components/CategoryPageHeader.tsx';
import { CategoryKpiStrip } from './components/CategoryKpiStrip.tsx';
import { CategoryCommandBar } from './components/CategoryCommandBar.tsx';
import { CategoryCard } from './components/CategoryCard.tsx';
import { CategoryTableView } from './components/CategoryTableView.tsx';
import { CategoryFormModal } from './components/CategoryFormModal.tsx';

export const Categories = () => {
  const { repositories } = useInfrastructure();
  const application = useApplication();
  const { user } = useAuth();

  const [categories, setCategories] = useState<CategoryView[]>([]);
  const [viewMode, setViewMode] = useState<CategoryViewMode>('grid');
  const [searchQuery, setSearchQuery] = useState('');
  const deferredSearch = useDeferredValue(searchQuery);
  const [sortBy, setSortBy] = useState<CategorySortKey>('recent');
  const [selectedCategoryId, setSelectedCategoryId] = useState<string | null>(null);
  const searchInputRef = useRef<HTMLInputElement>(null);
  const [isModalOpen, setIsModalOpen] = useState(false);
  const [isEditModalOpen, setIsEditModalOpen] = useState(false);
  const [editingCategoryId, setEditingCategoryId] = useState<string | null>(null);
  const [pendingCategoryIds, setPendingCategoryIds] = useState<Set<string>>(() => new Set());
  const optimisticCategoriesRef = useRef<Map<string, CategoryView>>(new Map());
  const [formData, setFormData] = useState<CategoryFormData>({
    name: '',
    description: '',
    image: null,
    imagePreview: '',
  });

  const displayedCategories = useMemo(() => {
    let list = categories.filter((cat) => cat.isActive);
    const query = deferredSearch.trim().toLowerCase();

    if (query) {
      list = list.filter(
        (cat) =>
          cat.name.toLowerCase().includes(query) || cat.description.toLowerCase().includes(query)
      );
    }

    return [...list].sort((a, b) => {
      if (sortBy === 'name') return a.name.localeCompare(b.name, 'es');
      if (sortBy === 'products') return b.productCount - a.productCount;
      const aDate = a.editedAt || a.createdAt;
      const bDate = b.editedAt || b.createdAt;
      return new Date(bDate).getTime() - new Date(aDate).getTime();
    });
  }, [categories, deferredSearch, sortBy]);

  const totalProducts = displayedCategories.reduce((sum, cat) => sum + cat.productCount, 0);
  const activeCategoryCount = categories.filter((c) => c.isActive).length;
  const isSearching = searchQuery !== deferredSearch;

  const mapServerCategories = (items: Category[]): CategoryView[] =>
          items.map((c) => ({
            ...c,
      products: Array.isArray((c as CategoryView).products) ? (c as CategoryView).products : [],
    }));

  useEffect(() => {
    const unsubscribe = repositories.category.subscribe(
      (items) => {
        const server = mapServerCategories(items);
        const serverIds = new Set(server.map((c) => c.id));

        serverIds.forEach((id) => optimisticCategoriesRef.current.delete(id));
        setPendingCategoryIds((prev) => {
          const next = new Set(prev);
          let changed = false;
          serverIds.forEach((id) => {
            if (next.delete(id)) changed = true;
          });
          return changed ? next : prev;
        });

        const pending = Array.from(optimisticCategoriesRef.current.values()).filter(
          (c) => !serverIds.has(c.id)
        );
        setCategories([...pending, ...server]);
      },
      (error) => console.error('Error subscribing categories:', error)
    );
    return () => unsubscribe();
  }, [repositories.category]);

  useEffect(() => {
    const HandleKeyboard = (e: KeyboardEvent) => {
      if ((e.ctrlKey || e.metaKey) && e.key.toLowerCase() === 'k') {
        e.preventDefault();
        searchInputRef.current?.focus();
      }
      if (e.key === 'Escape' && searchQuery) {
        setSearchQuery('');
      }
    };

    window.addEventListener('keydown', HandleKeyboard);
    return () => window.removeEventListener('keydown', HandleKeyboard);
  }, [searchQuery]);

  const showToast = (
    type: 'success' | 'error' | 'warning',
    message: string,
    duration: number = 3000
  ) => {
    const toastOptions = {
      duration,
      className: `toast-with-progress ${type}`,
      style: { '--toast-duration': `${duration}ms` } as React.CSSProperties,
    };

    switch (type) {
      case 'success':
        toast.success(message, toastOptions);
        break;
      case 'error':
        toast.error(message, toastOptions);
        break;
      case 'warning':
        toast(message, { ...toastOptions, icon: '⚠️' });
        break;
    }
  };

  const handleOpenModal = () => setIsModalOpen(true);

  const handleCloseModal = () => {
    setIsModalOpen(false);
    setFormData({ name: '', description: '', image: null, imagePreview: '' });
  };

  const handleOpenEditModal = (category: CategoryView) => {
    setSelectedCategoryId(category.id);
    setEditingCategoryId(category.id);
    setIsEditModalOpen(true);
    setFormData({
      name: category.name,
      description: category.description,
      image: category.image,
      imagePreview: category.image,
    });
  };

  const handleCloseEditModal = () => {
    setIsEditModalOpen(false);
    setEditingCategoryId(null);
    setSelectedCategoryId(null);
    setFormData({ name: '', description: '', image: null, imagePreview: '' });
  };

  const handleSelectCategory = (category: CategoryView) => {
    setSelectedCategoryId(category.id);
  };

  const handleImageUpload = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (!file) return;

    if (file.size > 5 * 1024 * 1024) {
      showToast('error', 'La imagen es demasiado grande. Máximo 5MB', 4000);
      return;
    }

    if (!file.type.startsWith('image/')) {
      showToast('error', 'Selecciona un archivo de imagen válido', 4000);
      return;
    }

    const reader = new FileReader();
    reader.onloadend = () => {
      setFormData((prev) => ({
        ...prev,
        image: file,
        imagePreview: reader.result as string,
      }));
    };
    reader.readAsDataURL(file);
  };

  const handleInputChange = (
    e: React.ChangeEvent<HTMLInputElement | HTMLTextAreaElement | HTMLSelectElement>
  ) => {
    const { name, value } = e.target;
    setFormData((prev) => ({ ...prev, [name]: value }));
  };

  const handleImageRemove = () => {
    setFormData((prev) => ({ ...prev, image: null, imagePreview: '' }));
  };

  const slugify = (value: string) => {
    const normalized = value
      .trim()
      .toLowerCase()
      .normalize('NFD')
      .replace(/[\u0300-\u036f]/g, '');

    const slug = normalized
      .replace(/[^a-z0-9\s-]/g, '')
      .replace(/\s+/g, '-')
      .replace(/-+/g, '-')
      .replace(/^-|-$/g, '');

    return slug || 'categoria';
  };

  const buildCategoryId = (name: string) => {
    const base = `cat-${slugify(name)}`.slice(0, 48);
    const existing = new Set(categories.map((c) => c.id));
    if (!existing.has(base)) return base;

    let suffix = 2;
    while (existing.has(`${base}-${suffix}`)) suffix++;
    return `${base}-${suffix}`;
  };

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    
    if (!formData.name.trim() || !formData.description.trim()) {
      showToast('error', 'Por favor completa todos los campos requeridos', 3000);
      return;
    }

    if (!formData.image && !formData.imagePreview) {
      showToast('error', 'Por favor selecciona una imagen para la categoría', 3000);
      return;
    }

    const trimmedName = formData.name.trim();
    const description = formData.description.trim();
    const imageFile = formData.image instanceof File ? formData.image : null;
    const previewImage =
      formData.imagePreview || (typeof formData.image === 'string' ? formData.image : '');

    const categoryId = buildCategoryId(trimmedName);
    const newIndex = categories.length;
    const styles = GetAutoGeneratedStyles(newIndex);
    const trendData = CalculateTrend(0, 0);
    const createdAt = new Date().toISOString();

    const optimisticCategory: CategoryView = {
      id: categoryId,
      name: trimmedName,
      description,
      productCount: 0,
      image: previewImage,
      color: styles.color,
      gradient: styles.gradient,
      trend: trendData.trend,
      trendValue: trendData.trendValue,
      createdAt,
      isActive: true,
      products: [],
    };

    optimisticCategoriesRef.current.set(categoryId, optimisticCategory);
    setPendingCategoryIds((prev) => new Set(prev).add(categoryId));
    setCategories((prev) => [optimisticCategory, ...prev.filter((c) => c.id !== categoryId)]);

    handleCloseModal();
    showToast('success', `Categoría "${trimmedName}" agregada — sincronizando en segundo plano`, 2500);

    void (async () => {
      try {
        let imageUrl = previewImage;
        if (imageFile) {
        imageUrl = await uploadCategoryImage({
          categoryName: trimmedName,
            file: imageFile,
          });
        }

        const newCategory: Category = {
          id: categoryId,
          name: trimmedName,
          description,
          productCount: 0,
          image: imageUrl,
          color: styles.color,
          gradient: styles.gradient,
          trend: trendData.trend,
          trendValue: trendData.trendValue,
          createdAt,
          isActive: true,
        };

        await application.categories.create.execute({
          category: newCategory,
          actorEmail: user?.email,
          actorName: user?.name,
        });
      } catch (error: unknown) {
        optimisticCategoriesRef.current.delete(categoryId);
        setPendingCategoryIds((prev) => {
          const next = new Set(prev);
          next.delete(categoryId);
          return next;
        });
        setCategories((prev) => prev.filter((c) => c.id !== categoryId));

        const err = error as { message?: string };
        console.error('Error creating category:', error);
        let errorMessage = 'No se pudo guardar la categoría.';

        if (err?.message?.includes('longer than')) {
          errorMessage = 'La imagen es demasiado grande. Máximo 5MB.';
        } else if (err?.message) {
          errorMessage = err.message;
        }

        showToast('error', errorMessage, 5000);
      }
    })();
  };

  const handleEditSubmit = (e: React.FormEvent) => {
    e.preventDefault();

    if (!formData.name.trim() || !formData.description.trim()) {
      showToast('error', 'Por favor completa todos los campos requeridos', 3000);
        return;
      }

    if (!formData.image && !formData.imagePreview) {
      showToast('error', 'Por favor selecciona una imagen para la categoría', 3000);
      return;
    }

    if (!editingCategoryId) return;

    const existing = categories.find((c) => c.id === editingCategoryId);
    if (!existing) return;

    const categoryId = editingCategoryId;
    const trimmedName = formData.name.trim();
    const description = formData.description.trim();
    const imageFile = formData.image instanceof File ? formData.image : null;
    const previewImage =
      formData.imagePreview || (typeof formData.image === 'string' ? formData.image : '');
    const editedAt = new Date().toISOString();
    const rollbackSnapshot: CategoryView = { ...existing };

    const optimisticCategory: CategoryView = {
      ...existing,
      name: trimmedName,
      description,
      image: previewImage,
      editedAt,
    };

    setPendingCategoryIds((prev) => new Set(prev).add(categoryId));
    setCategories((prev) =>
      prev.map((c) => (c.id === categoryId ? optimisticCategory : c))
    );

    handleCloseEditModal();
    showToast('success', `Categoría "${trimmedName}" actualizada — sincronizando en segundo plano`, 2500);

    void (async () => {
      try {
        let imageUrl = previewImage;
        if (imageFile) {
          imageUrl = await uploadCategoryImage({
            categoryName: trimmedName,
            file: imageFile,
          });
        }

        const beforeSnapshot: Record<string, unknown> = {
          Nombre: existing.name,
          Descripción: existing.description,
          Imagen: existing.image ? 'Sí' : 'No',
        };
        const afterSnapshot: Record<string, unknown> = {
          Nombre: trimmedName,
          Descripción: description,
          Imagen: imageUrl ? 'Sí' : 'No',
        };

        await application.categories.update.execute({
          categoryId,
          patch: {
            name: trimmedName,
            description,
            image: imageUrl,
            editedAt,
          },
          itemName: trimmedName,
          beforeSnapshot,
          afterSnapshot,
          actorEmail: user?.email,
          actorName: user?.name,
        });
      } catch (error: unknown) {
        setCategories((prev) =>
          prev.map((c) => (c.id === categoryId ? rollbackSnapshot : c))
        );
        setPendingCategoryIds((prev) => {
          const next = new Set(prev);
          next.delete(categoryId);
          return next;
        });

        const err = error as { message?: string; code?: string };
        console.error('Error updating category:', error);
        let errorMessage = 'No se pudo guardar los cambios de la categoría.';

        if (
          err?.message?.includes('autenticado') ||
          err?.code?.includes('unauthorized') ||
          err?.code?.includes('unauthenticated')
        ) {
          errorMessage = 'Debes iniciar sesión con Google para subir imágenes.';
        } else if (err?.code?.includes('permission')) {
          errorMessage = 'Error de permisos en Firebase Storage.';
        } else if (err?.message) {
          errorMessage = err.message;
        }

        showToast('error', errorMessage, 5000);
      }
    })();
  };

  const handleDeleteCategory = async (category: CategoryView) => {
    if (category.productCount > 0) {
      const result = await Swal.fire({
        title: '¿Desactivar categoría?',
        html: `
          <div style="text-align: center;">
            <p style="font-size: 1.1rem; margin-bottom: 1rem;">
              La categoría <strong style="color: #f59e0b;">"${category.name}"</strong> tiene <strong>${category.productCount} productos</strong> asociados.
            </p>
            <p style="color: #92400e; font-size: 0.9rem; background: #fffbeb; padding: 0.75rem; border-radius: 0.5rem; border-left: 3px solid #f59e0b;">
              ⚠️ Se desactivará (no se eliminará). Los productos mantendrán su relación.
            </p>
          </div>
        `,
        icon: 'warning',
        iconColor: '#f59e0b',
        showCancelButton: true,
        confirmButtonColor: '#f59e0b',
        cancelButtonColor: '#6b7280',
        confirmButtonText: 'Sí, desactivar',
        cancelButtonText: 'Cancelar',
        reverseButtons: true,
        focusConfirm: false,
      });

      if (result.isConfirmed) {
        try {
          await repositories.category.update(category.id, { isActive: false });
        } catch (error) {
          console.error('Error deactivating category:', error);
          showToast('error', 'No se pudo desactivar la categoría', 3000);
          return;
        }

        await application.history.log.execute({
          action: 'deactivate',
          section: 'categories',
          itemName: category.name,
          itemId: category.id,
          details: `Categoría "${category.name}" desactivada`,
          actorEmail: user?.email,
          actorName: user?.name,
          actorType: 'admin',
        });

        showToast('success', `Categoría "${category.name}" desactivada exitosamente`, 3000);
      }
    } else {
      const result = await Swal.fire({
        title: '¿Eliminar permanentemente?',
        html: `
          <div style="text-align: center;">
            <p style="font-size: 1.1rem; margin-bottom: 1rem;">
              La categoría <strong style="color: #ef4444;">"${category.name}"</strong> será eliminada permanentemente.
            </p>
            <p style="color: #991b1b; font-size: 0.9rem; background: #fef2f2; padding: 0.75rem; border-radius: 0.5rem; border-left: 3px solid #ef4444;">
              ⚠️ Esta acción no se puede deshacer.
            </p>
          </div>
        `,
        icon: 'warning',
        iconColor: '#ef4444',
        showCancelButton: true,
        confirmButtonColor: '#ef4444',
        cancelButtonColor: '#6b7280',
        confirmButtonText: 'Sí, eliminar',
        cancelButtonText: 'Cancelar',
        reverseButtons: true,
        focusConfirm: false,
      });

      if (result.isConfirmed) {
        try {
          showToast('success', `Eliminando imagen de "${category.name}" del Storage...`, 2000);
          try {
            await deleteCategoryStorageAssets({
              categoryName: category.name,
              imageUrl: category.image,
            });
          } catch (storageError) {
            console.error('Error eliminando assets de categoría del Storage:', storageError);
            showToast(
              'warning',
              'La categoría se eliminará pero la imagen puede no haberse borrado del Storage',
              4000
            );
          }

          await application.categories.delete.execute({
            categoryId: category.id,
        itemName: category.name,
            actorEmail: user?.email,
            actorName: user?.name,
          });
        } catch (error) {
          console.error('Error deleting category:', error);
          showToast('error', 'No se pudo eliminar la categoría', 3000);
        return;
      }
      
        showToast('success', `Categoría "${category.name}" eliminada permanentemente`, 3000);
      }
    }
  };

  return (
    <div className="categories-page">
      <CategoryPageHeader OnOpenCreate={handleOpenModal} />

      <CategoryKpiStrip
        TotalCategories={displayedCategories.length}
        TotalProducts={totalProducts}
        AverageProducts={
          displayedCategories.length > 0
            ? Math.round(totalProducts / displayedCategories.length)
            : 0
        }
        ActiveCount={activeCategoryCount}
      />

      <CategoryCommandBar
        SearchQuery={searchQuery}
        OnSearchChange={setSearchQuery}
        OnClearSearch={() => setSearchQuery('')}
        IsSearching={isSearching}
        ViewMode={viewMode}
        OnViewModeChange={setViewMode}
        SortBy={sortBy}
        OnSortChange={setSortBy}
        ResultCount={displayedCategories.length}
        SearchInputRef={searchInputRef}
      />

      {viewMode === 'table' ? (
        <CategoryTableView
          Categories={displayedCategories}
          PendingCategoryIds={pendingCategoryIds}
          SelectedCategoryId={selectedCategoryId}
          OnSelect={handleSelectCategory}
          OnEdit={handleOpenEditModal}
          OnDelete={handleDeleteCategory}
          HasSearch={searchQuery.trim().length > 0}
        />
      ) : (
        <div className="categories-grid">
          {displayedCategories.map((category, index) => {
            const sharePercentage =
              totalProducts > 0 ? (category.productCount / totalProducts) * 100 : 0;
          
          return (
              <CategoryCard
              key={category.id}
                Category={category}
                Index={index}
                IsPending={pendingCategoryIds.has(category.id)}
                IsSelected={selectedCategoryId === category.id}
                SharePercentage={sharePercentage}
                OnSelect={handleSelectCategory}
                OnEdit={handleOpenEditModal}
                OnDelete={handleDeleteCategory}
              />
            );
          })}
          {displayedCategories.length === 0 && (
            <div className="categories-empty" style={{ gridColumn: '1 / -1' }}>
              <span className="categories-empty__emoji" aria-hidden="true">
                📂
                      </span>
              <h3>Sin resultados</h3>
              <p>
                {searchQuery.trim()
                  ? 'No hay categorías activas que coincidan con tu búsqueda.'
                  : 'Aún no hay categorías activas. Crea la primera desde el botón superior.'}
              </p>
              {!searchQuery.trim() && (
                <button type="button" className="categories-empty__cta" onClick={handleOpenModal}>
                  Crear primera categoría
                    </button>
                  )}
        </div>
      )}
                  </div>
                )}

      <CategoryFormModal
        Mode="create"
        IsOpen={isModalOpen}
        FormData={formData}
        OnClose={handleCloseModal}
        OnSubmit={handleSubmit}
        OnInputChange={handleInputChange}
        OnImageUpload={handleImageUpload}
        OnImageRemove={handleImageRemove}
      />

      <CategoryFormModal
        Mode="edit"
        IsOpen={isEditModalOpen}
        FormData={formData}
        OnClose={handleCloseEditModal}
        OnSubmit={handleEditSubmit}
        OnInputChange={handleInputChange}
        OnImageUpload={handleImageUpload}
        OnImageRemove={handleImageRemove}
      />
    </div>
  );
};
