export const CategoryGradientOptions = [
  'linear-gradient(135deg, #14b8a6 0%, #0d9488 100%)',
  'linear-gradient(135deg, #2dd4bf 0%, #0891b2 100%)',
  'linear-gradient(135deg, #5eead4 0%, #06b6d4 100%)',
  'linear-gradient(135deg, #0f766e 0%, #155e75 100%)',
  'linear-gradient(135deg, #22d3ee 0%, #0e7490 100%)',
  'linear-gradient(135deg, #99f6e4 0%, #67e8f9 100%)',
] as const;

export const CategoryColorOptions = [
  '#0d9488',
  '#14b8a6',
  '#0891b2',
  '#0f766e',
  '#06b6d4',
  '#2dd4bf',
] as const;

export { FormatDate, GetTrendIcon, GetTrendColor, CalculateTrend } from '../../Brands/utils/brandPresentationUtils.ts';

export const GetAutoGeneratedStyles = (index: number) => {
  const gradientIndex = index % CategoryGradientOptions.length;
  return {
    gradient: CategoryGradientOptions[gradientIndex],
    color: CategoryColorOptions[gradientIndex],
  };
};
