export const GradientOptions = [
  'linear-gradient(135deg, #667eea 0%, #764ba2 100%)',
  'linear-gradient(135deg, #f093fb 0%, #f5576c 100%)',
  'linear-gradient(135deg, #4facfe 0%, #00f2fe 100%)',
  'linear-gradient(135deg, #fa709a 0%, #fee140 100%)',
  'linear-gradient(135deg, #30cfd0 0%, #330867 100%)',
  'linear-gradient(135deg, #a8edea 0%, #fed6e3 100%)',
] as const;

export const ColorOptions = [
  '#3b82f6',
  '#10b981',
  '#f59e0b',
  '#8b5cf6',
  '#ef4444',
  '#06b6d4',
] as const;

export const FormatDate = (dateString: string): string => {
  if (!dateString) return '';
  const date = new Date(dateString);
  if (isNaN(date.getTime())) return dateString;
  const day = String(date.getDate()).padStart(2, '0');
  const month = String(date.getMonth() + 1).padStart(2, '0');
  const year = date.getFullYear();
  const hours = String(date.getHours()).padStart(2, '0');
  const minutes = String(date.getMinutes()).padStart(2, '0');
  return `${day}/${month}/${year} ${hours}:${minutes}`;
};

export const GetTrendIcon = (trend: string): string => {
  switch (trend) {
    case 'up':
      return '↗';
    case 'down':
      return '↘';
    default:
      return '→';
  }
};

export const GetTrendColor = (trend: string): string => {
  switch (trend) {
    case 'up':
      return '#10b981';
    case 'down':
      return '#ef4444';
    default:
      return '#64748b';
  }
};

export const GetAutoGeneratedStyles = (index: number) => {
  const gradientIndex = index % GradientOptions.length;
  return {
    gradient: GradientOptions[gradientIndex],
    color: ColorOptions[gradientIndex],
  };
};

export const CalculateTrend = (currentCount: number, previousCount: number) => {
  if (previousCount === 0) {
    return { trend: 'stable' as const, trendValue: 0 };
  }
  const change = ((currentCount - previousCount) / previousCount) * 100;
  const roundedChange = Math.round(change);
  if (roundedChange > 0) {
    return { trend: 'up' as const, trendValue: roundedChange };
  }
  if (roundedChange < 0) {
    return { trend: 'down' as const, trendValue: roundedChange };
  }
  return { trend: 'stable' as const, trendValue: 0 };
};
