import { useEffect, useState, useRef, useMemo, useDeferredValue } from 'react';
import toast from 'react-hot-toast';
import Swal from 'sweetalert2';
import './Brands.css';
import { useApplication, useInfrastructure } from '../../providers/DependencyProvider.tsx';
import { useAuth } from '../../context/AuthContext.tsx';
import type { Brand } from '../../../domain/entities/Brand.ts';
import { uploadBrandImage, deleteBrandStorageAssets } from '../../../infrastructure/index.ts';
import type { BrandFormData, BrandSortKey, BrandView, BrandViewMode, CategoryOption } from './types/BrandPageTypes.ts';
import { CalculateTrend, GetAutoGeneratedStyles } from './utils/brandPresentationUtils.ts';
import { BrandPageHeader } from './components/BrandPageHeader.tsx';
import { BrandKpiStrip } from './components/BrandKpiStrip.tsx';
import { BrandCommandBar } from './components/BrandCommandBar.tsx';
import { BrandCard } from './components/BrandCard.tsx';
import { BrandTableView } from './components/BrandTableView.tsx';
import { BrandFormModal } from './components/BrandFormModal.tsx';

export const Brands = () => {
  const { repositories } = useInfrastructure();
  const application = useApplication();
  const { user } = useAuth();

  const [brands, setBrands] = useState<BrandView[]>([]);
  const [categories, setCategories] = useState<CategoryOption[]>([]);
  const [viewMode, setViewMode] = useState<BrandViewMode>('grid');
  const [searchQuery, setSearchQuery] = useState('');
  const deferredSearch = useDeferredValue(searchQuery);
  const [sortBy, setSortBy] = useState<BrandSortKey>('recent');
  const [selectedBrandId, setSelectedBrandId] = useState<string | null>(null);
  const searchInputRef = useRef<HTMLInputElement>(null);
  const [isModalOpen, setIsModalOpen] = useState(false);
  const [isEditModalOpen, setIsEditModalOpen] = useState(false);
  const [editingBrandId, setEditingBrandId] = useState<string | null>(null);
  const [pendingBrandIds, setPendingBrandIds] = useState<Set<string>>(() => new Set());
  const optimisticBrandsRef = useRef<Map<string, BrandView>>(new Map());
  const [formData, setFormData] = useState<BrandFormData>({
    name: '',
    description: '',
    categoryIds: [],
    image: null,
    imagePreview: '',
    imageFit: 'cover',
  });

  const activeCategories = categories.filter((cat) => cat.isActive);

  const getCategoryLabels = (ids: string[]) => {
    const labels = ids
      .map((id) => categories.find((cat) => cat.id === id)?.name)
      .filter(Boolean) as string[];
    return labels.length ? labels.join(', ') : 'Sin categoría';
  };

  const displayedBrands = useMemo(() => {
    let list = brands.filter((brand) => brand.isActive);
    const query = deferredSearch.trim().toLowerCase();

    if (query) {
      list = list.filter(
        (brand) =>
          brand.name.toLowerCase().includes(query) ||
          brand.description.toLowerCase().includes(query) ||
          getCategoryLabels(brand.categoryIds).toLowerCase().includes(query)
      );
    }

    return [...list].sort((a, b) => {
      if (sortBy === 'name') return a.name.localeCompare(b.name, 'es');
      if (sortBy === 'products') return b.productCount - a.productCount;
      const aDate = a.editedAt || a.createdAt;
      const bDate = b.editedAt || b.createdAt;
      return new Date(bDate).getTime() - new Date(aDate).getTime();
    });
  }, [brands, deferredSearch, sortBy, categories]);

  const totalProducts = displayedBrands.reduce((sum, brand) => sum + brand.productCount, 0);
  const activeBrandCount = brands.filter((b) => b.isActive).length;
  const isSearching = searchQuery !== deferredSearch;

  const mapServerBrands = (items: Brand[]): BrandView[] =>
    items.map((b) => ({
      ...b,
      categoryIds: Array.isArray(b.categoryIds) ? b.categoryIds : [],
      imageFit: b.imageFit ?? 'cover',
      products: Array.isArray((b as BrandView).products) ? (b as BrandView).products : [],
    }));

  useEffect(() => {
    const unsubscribe = repositories.brand.subscribe(
      (items) => {
        const server = mapServerBrands(items);
        const serverIds = new Set(server.map((b) => b.id));

        serverIds.forEach((id) => optimisticBrandsRef.current.delete(id));
        setPendingBrandIds((prev) => {
          const next = new Set(prev);
          let changed = false;
          serverIds.forEach((id) => {
            if (next.delete(id)) changed = true;
          });
          return changed ? next : prev;
        });

        const pending = Array.from(optimisticBrandsRef.current.values()).filter(
          (b) => !serverIds.has(b.id)
        );
        setBrands([...pending, ...server]);
      },
      (error) => console.error('Error subscribing brands:', error)
    );
    return () => unsubscribe();
  }, [repositories.brand]);

  useEffect(() => {
    const unsubscribe = repositories.category.subscribe(
      (items) => setCategories(items),
      (error) => console.error('Error subscribing categories:', error)
    );
    return () => unsubscribe();
  }, [repositories.category]);

  useEffect(() => {
    const HandleKeyboard = (e: KeyboardEvent) => {
      if ((e.ctrlKey || e.metaKey) && e.key.toLowerCase() === 'k') {
        e.preventDefault();
        searchInputRef.current?.focus();
      }
      if (e.key === 'Escape' && searchQuery) {
        setSearchQuery('');
      }
    };

    window.addEventListener('keydown', HandleKeyboard);
    return () => window.removeEventListener('keydown', HandleKeyboard);
  }, [searchQuery]);

  const showToast = (
    type: 'success' | 'error' | 'warning',
    message: string,
    duration: number = 3000
  ) => {
    const toastOptions = {
      duration,
      className: `toast-with-progress ${type}`,
      style: {
        '--toast-duration': `${duration}ms`,
      } as React.CSSProperties,
    };

    switch (type) {
      case 'success':
        toast.success(message, toastOptions);
        break;
      case 'error':
        toast.error(message, toastOptions);
        break;
      case 'warning':
        toast(message, { ...toastOptions, icon: '⚠️' });
        break;
    }
  };

  const handleOpenModal = () => {
    setIsModalOpen(true);
  };

  const handleCloseModal = () => {
    setIsModalOpen(false);
    setFormData({
      name: '',
      description: '',
      categoryIds: [],
      image: null,
      imagePreview: '',
      imageFit: 'cover',
    });
  };

  const handleOpenEditModal = (brand: BrandView) => {
    setSelectedBrandId(brand.id);
    setEditingBrandId(brand.id);
    setIsEditModalOpen(true);
    setFormData({
      name: brand.name,
      description: brand.description,
      categoryIds: brand.categoryIds,
      image: brand.image,
      imagePreview: brand.image,
      imageFit: brand.imageFit ?? 'cover',
    });
  };

  const handleCloseEditModal = () => {
    setIsEditModalOpen(false);
    setEditingBrandId(null);
    setSelectedBrandId(null);
    setFormData({
      name: '',
      description: '',
      categoryIds: [],
      image: null,
      imagePreview: '',
      imageFit: 'cover',
    });
  };

  const handleSelectBrand = (brand: BrandView) => {
    setSelectedBrandId(brand.id);
  };

  const handleImageUpload = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (file) {
      if (file.size > 5 * 1024 * 1024) {
        showToast('error', 'La imagen es demasiado grande. Por favor selecciona una imagen menor a 5MB', 4000);
        return;
      }
      
      if (!file.type.startsWith('image/')) {
        showToast('error', 'Por favor selecciona un archivo de imagen válido (PNG, JPG, WEBP, etc.)', 4000);
        return;
      }

      const reader = new FileReader();
      reader.onloadend = () => {
        setFormData((prev) => ({
          ...prev,
          image: file,
          imagePreview: reader.result as string,
        }));
      };
      reader.readAsDataURL(file);
    }
  };

  const handleInputChange = (
    e: React.ChangeEvent<HTMLInputElement | HTMLTextAreaElement | HTMLSelectElement>
  ) => {
    const { name, value } = e.target;
    setFormData((prev) => ({
      ...prev,
      [name]: value,
    }));
  };

  const toggleCategoryId = (categoryId: string, checked: boolean) => {
    setFormData((prev) => {
      const next = new Set(prev.categoryIds);
      if (checked) {
        next.add(categoryId);
      } else {
        next.delete(categoryId);
      }
      return { ...prev, categoryIds: Array.from(next) };
    });
  };

  const handleImageRemove = () => {
    setFormData((prev) => ({
      ...prev,
      image: null,
      imagePreview: '',
    }));
  };

  const slugify = (value: string) => {
    const normalized = value
      .trim()
      .toLowerCase()
      .normalize('NFD')
      .replace(/[\u0300-\u036f]/g, '');

    const slug = normalized
      .replace(/[^a-z0-9\s-]/g, '')
      .replace(/\s+/g, '-')
      .replace(/-+/g, '-')
      .replace(/^-|-$/g, '');

    return slug || 'marca';
  };

  const buildBrandId = (name: string) => {
    const base = `marca-${slugify(name)}`.slice(0, 48);
    const existing = new Set(brands.map((b) => b.id));
    if (!existing.has(base)) return base;

    let suffix = 2;
    while (existing.has(`${base}-${suffix}`)) {
      suffix++;
    }
    return `${base}-${suffix}`;
  };

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    
    if (!formData.name.trim() || !formData.description.trim() || formData.categoryIds.length === 0) {
      showToast('error', 'Por favor completa todos los campos requeridos', 3000);
      return;
    }

    if (!formData.image && !formData.imagePreview) {
      showToast('error', 'Por favor selecciona una imagen para la marca', 3000);
      return;
    }

    const trimmedName = formData.name.trim();
    const description = formData.description.trim();
    const categoryIds = [...formData.categoryIds];
    const imageFit = formData.imageFit;
    const imageFile = formData.image instanceof File ? formData.image : null;
    const previewImage =
      formData.imagePreview || (typeof formData.image === 'string' ? formData.image : '');

    const brandId = buildBrandId(trimmedName);
    const newIndex = brands.length;
    const styles = GetAutoGeneratedStyles(newIndex);
    const trendData = CalculateTrend(0, 0);
    const createdAt = new Date().toISOString();

    const optimisticBrand: BrandView = {
      id: brandId,
      name: trimmedName,
      description,
      categoryIds,
      productCount: 0,
      image: previewImage,
      imageFit,
      color: styles.color,
      gradient: styles.gradient,
      trend: trendData.trend,
      trendValue: trendData.trendValue,
      createdAt,
      isActive: true,
      products: [],
    };

    optimisticBrandsRef.current.set(brandId, optimisticBrand);
    setPendingBrandIds((prev) => new Set(prev).add(brandId));
    setBrands((prev) => [optimisticBrand, ...prev.filter((b) => b.id !== brandId)]);

    handleCloseModal();
    showToast('success', `Marca "${trimmedName}" agregada — sincronizando en segundo plano`, 2500);

    void (async () => {
      try {
        let imageUrl = previewImage;
        if (imageFile) {
          imageUrl = await uploadBrandImage({
            brandName: trimmedName,
            file: imageFile,
          });
        }

        const newBrand: Brand = {
          id: brandId,
          name: trimmedName,
          description,
          categoryIds,
          productCount: 0,
          image: imageUrl,
          imageFit,
          color: styles.color,
          gradient: styles.gradient,
          trend: trendData.trend,
          trendValue: trendData.trendValue,
          createdAt,
          isActive: true,
        };

        await application.brands.create.execute({
          brand: newBrand,
          actorEmail: user?.email,
          actorName: user?.name,
        });
      } catch (error: unknown) {
        optimisticBrandsRef.current.delete(brandId);
        setPendingBrandIds((prev) => {
          const next = new Set(prev);
          next.delete(brandId);
          return next;
        });
        setBrands((prev) => prev.filter((b) => b.id !== brandId));

        const err = error as { message?: string };
        console.error('Error creating brand:', error);
        let errorMessage = 'No se pudo guardar la marca.';

        if (err?.message?.includes('longer than')) {
          errorMessage = 'La imagen es demasiado grande. Por favor selecciona una imagen más pequeña (máximo 5MB).';
        } else if (err?.message) {
          errorMessage = err.message;
        }

        showToast('error', errorMessage, 5000);
      }
    })();
  };

  const handleEditSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    
    if (!formData.name.trim() || !formData.description.trim() || formData.categoryIds.length === 0) {
      showToast('error', 'Por favor completa todos los campos requeridos', 3000);
      return;
    }

    if (!formData.image && !formData.imagePreview) {
      showToast('error', 'Por favor selecciona una imagen para la marca', 3000);
      return;
    }

    if (!editingBrandId) return;

    const existing = brands.find((b) => b.id === editingBrandId);
    if (!existing) return;

    const trimmedName = formData.name.trim();
    let imageUrl: string;

    // Si hay un archivo nuevo, subirlo a Storage
    if (formData.image instanceof File) {
      try {
        showToast('success', 'Subiendo imagen...', 2000);
        imageUrl = await uploadBrandImage({
          brandName: trimmedName,
          file: formData.image,
        });
      } catch (error: any) {
        console.error('Error uploading brand image:', error);
        let errorMessage = 'No se pudo subir la imagen de la marca.';
        
        if (error?.message?.includes('autenticado') || error?.code?.includes('unauthorized') || error?.code?.includes('unauthenticated')) {
          errorMessage = 'Error al subir imagen: Debes iniciar sesión con Google para subir imágenes.';
        } else if (error?.code?.includes('permission')) {
          errorMessage = 'Error de permisos: Verifica las reglas de Storage en Firebase Console.';
        } else if (error?.message) {
          errorMessage = error.message;
        }
        
        showToast('error', errorMessage, 6000);
        return;
      }
    } else {
      // Si ya es una URL (no cambió la imagen), usar la URL existente
      imageUrl = formData.imagePreview || (formData.image as string);
    }

    const editedAt = new Date().toISOString();

    // Preparar objeto "antes" para comparación
    const beforeCategoryNames = existing.categoryIds
      .map((id) => categories.find((c) => c.id === id)?.name || id)
      .join(', ');
    
    const beforeSnapshot: Record<string, unknown> = {
      Nombre: existing.name,
      Descripción: existing.description,
      Categorías: beforeCategoryNames || 'Ninguna',
      Imagen: existing.image ? 'Sí' : 'No',
    };

    const afterCategoryNames = formData.categoryIds
      .map((id) => categories.find((c) => c.id === id)?.name || id)
      .join(', ');

    const afterSnapshot: Record<string, unknown> = {
      Nombre: formData.name.trim(),
      Descripción: formData.description.trim(),
      Categorías: afterCategoryNames || 'Ninguna',
      Imagen: imageUrl ? 'Sí' : 'No',
    };

    try {
      await application.brands.update.execute({
        brandId: editingBrandId,
        patch: {
          name: formData.name.trim(),
          description: formData.description.trim(),
          categoryIds: formData.categoryIds,
          image: imageUrl,
          imageFit: formData.imageFit,
          editedAt,
        },
        itemName: formData.name.trim(),
        beforeSnapshot,
        afterSnapshot,
        actorEmail: user?.email,
        actorName: user?.name,
      });
    } catch (error) {
      console.error('Error updating brand:', error);
      showToast('error', 'No se pudo editar la marca', 3000);
      return;
    }

    showToast('success', `Marca "${formData.name.trim()}" editada exitosamente`, 3000);
    
    handleCloseEditModal();
  };

  const handleDeleteBrand = async (brand: BrandView) => {
    if (brand.productCount > 0) {
      const result = await Swal.fire({
        title: '¿Desactivar marca?',
        html: `
          <div style="text-align: center;">
            <p style="font-size: 1.1rem; margin-bottom: 1rem;">
              La marca <strong style="color: #f59e0b;">"${brand.name}"</strong> tiene <strong>${brand.productCount} productos</strong> asociados.
            </p>
            <p style="color: #92400e; font-size: 0.9rem; background: #fffbeb; padding: 0.75rem; border-radius: 0.5rem; border-left: 3px solid #f59e0b;">
              ⚠️ Se desactivará la marca (no se eliminará). Los productos mantendrán su relación y podrás reactivarla después.
            </p>
          </div>
        `,
        icon: 'warning',
        iconColor: '#f59e0b',
        showCancelButton: true,
        confirmButtonColor: '#f59e0b',
        cancelButtonColor: '#6b7280',
        confirmButtonText: 'Sí, desactivar',
        cancelButtonText: 'Cancelar',
        reverseButtons: true,
        focusConfirm: false,
        customClass: {
          popup: 'swal2-popup-custom',
          confirmButton: 'swal2-confirm-custom',
          cancelButton: 'swal2-cancel-custom',
        },
      });

      if (result.isConfirmed) {
        try {
          await repositories.brand.update(brand.id, { isActive: false });
        } catch (error) {
          console.error('Error deactivating brand:', error);
          showToast('error', 'No se pudo desactivar la marca', 3000);
          return;
        }

        await Swal.fire({
          title: '¡Desactivada!',
          text: `La marca "${brand.name}" ha sido desactivada`,
          icon: 'success',
          confirmButtonColor: '#10b981',
          confirmButtonText: 'Perfecto',
          timer: 2000,
          timerProgressBar: true,
        });

        await application.history.log.execute({
          action: 'deactivate',
          section: 'brands',
          itemName: brand.name,
          itemId: brand.id,
          details: `Marca "${brand.name}" desactivada`,
          actorEmail: user?.email,
          actorName: user?.name,
          actorType: 'admin',
        });

        showToast('success', `Marca "${brand.name}" desactivada exitosamente`, 3000);
      }
    } else {
      const result = await Swal.fire({
        title: '¿Eliminar permanentemente?',
        html: `
          <div style="text-align: center;">
            <p style="font-size: 1.1rem; margin-bottom: 1rem;">
              La marca <strong style="color: #ef4444;">"${brand.name}"</strong> será eliminada permanentemente.
            </p>
            <p style="color: #991b1b; font-size: 0.9rem; background: #fef2f2; padding: 0.75rem; border-radius: 0.5rem; border-left: 3px solid #ef4444;">
              ⚠️ Esta acción no se puede deshacer.
            </p>
          </div>
        `,
        icon: 'warning',
        iconColor: '#ef4444',
        showCancelButton: true,
        confirmButtonColor: '#ef4444',
        cancelButtonColor: '#6b7280',
        confirmButtonText: 'Sí, eliminar',
        cancelButtonText: 'Cancelar',
        reverseButtons: true,
        focusConfirm: false,
        customClass: {
          popup: 'swal2-popup-custom',
          confirmButton: 'swal2-confirm-custom',
          cancelButton: 'swal2-cancel-custom',
        },
      });

      if (result.isConfirmed) {
        try {
          showToast('success', `Eliminando imagen de "${brand.name}" del Storage...`, 2000);
          try {
            await deleteBrandStorageAssets({
              brandName: brand.name,
              imageUrl: brand.image,
            });
          } catch (storageError) {
            console.error('Error eliminando assets de marca del Storage:', storageError);
            showToast(
              'warning',
              'La marca se eliminará pero la imagen puede no haberse borrado del Storage',
              4000
            );
          }

          await application.brands.delete.execute({
            brandId: brand.id,
            itemName: brand.name,
            actorEmail: user?.email,
            actorName: user?.name,
          });
        } catch (error) {
          console.error('Error deleting brand:', error);
          showToast('error', 'No se pudo eliminar la marca', 3000);
          return;
        }

        await Swal.fire({
          title: '¡Eliminada!',
          text: `La marca "${brand.name}" ha sido eliminada permanentemente`,
          icon: 'success',
          confirmButtonColor: '#10b981',
          confirmButtonText: 'Perfecto',
          timer: 2000,
          timerProgressBar: true,
        });

        showToast('success', `Marca "${brand.name}" eliminada permanentemente`, 3000);
      }
    }
  };

  return (
    <div className="brands-page">
      <BrandPageHeader OnOpenCreate={handleOpenModal} />

      <BrandKpiStrip
        TotalBrands={displayedBrands.length}
        TotalProducts={totalProducts}
        AverageProducts={
          displayedBrands.length > 0 ? Math.round(totalProducts / displayedBrands.length) : 0
        }
        ActiveCount={activeBrandCount}
      />

      <BrandCommandBar
        SearchQuery={searchQuery}
        OnSearchChange={setSearchQuery}
        OnClearSearch={() => setSearchQuery('')}
        IsSearching={isSearching}
        ViewMode={viewMode}
        OnViewModeChange={setViewMode}
        SortBy={sortBy}
        OnSortChange={setSortBy}
        ResultCount={displayedBrands.length}
        SearchInputRef={searchInputRef}
      />

      {viewMode === 'table' ? (
        <BrandTableView
          Brands={displayedBrands}
          PendingBrandIds={pendingBrandIds}
          SelectedBrandId={selectedBrandId}
          GetCategoryLabels={getCategoryLabels}
          OnSelect={handleSelectBrand}
          OnEdit={handleOpenEditModal}
          OnDelete={handleDeleteBrand}
          HasSearch={searchQuery.trim().length > 0}
        />
      ) : (
        <div className="brands-grid">
          {displayedBrands.map((brand, index) => {
            const sharePercentage =
              totalProducts > 0 ? (brand.productCount / totalProducts) * 100 : 0;

            return (
              <BrandCard
                key={brand.id}
                Brand={brand}
                Index={index}
                IsPending={pendingBrandIds.has(brand.id)}
                IsSelected={selectedBrandId === brand.id}
                SharePercentage={sharePercentage}
                CategoryLabel={getCategoryLabels(brand.categoryIds)}
                OnSelect={handleSelectBrand}
                OnEdit={handleOpenEditModal}
                OnDelete={handleDeleteBrand}
              />
            );
          })}
          {displayedBrands.length === 0 && (
            <div className="brands-empty" style={{ gridColumn: '1 / -1' }}>
              <span className="brands-empty__emoji" aria-hidden="true">
                🏷️
              </span>
              <h3>Sin resultados</h3>
              <p>
                {searchQuery.trim()
                  ? 'No hay marcas activas que coincidan con tu búsqueda.'
                  : 'Aún no hay marcas activas. Crea la primera desde el botón superior.'}
              </p>
              {!searchQuery.trim() && (
                <button type="button" className="brands-empty__cta" onClick={handleOpenModal}>
                  Crear primera marca
                </button>
              )}
            </div>
          )}
        </div>
      )}

      <BrandFormModal
        Mode="create"
        IsOpen={isModalOpen}
        FormData={formData}
        ActiveCategories={activeCategories}
        OnClose={handleCloseModal}
        OnSubmit={handleSubmit}
        OnInputChange={handleInputChange}
        OnToggleCategory={toggleCategoryId}
        OnImageUpload={handleImageUpload}
        OnImageRemove={handleImageRemove}
      />

      <BrandFormModal
        Mode="edit"
        IsOpen={isEditModalOpen}
        FormData={formData}
        ActiveCategories={activeCategories}
        OnClose={handleCloseEditModal}
        OnSubmit={handleEditSubmit}
        OnInputChange={handleInputChange}
        OnToggleCategory={toggleCategoryId}
        OnImageUpload={handleImageUpload}
        OnImageRemove={handleImageRemove}
      />
    </div>
  );
};
